// SIPster Song-Datenbank
// Jeder Eintrag: Titel, Interpret, Jahr (Original-Veröffentlichung).
// Wird zur Laufzeit per YouTube-Suche aufgelöst - hier stehen bewusst
// KEINE Video-IDs, damit niemand (auch nicht im Code) vorab sieht,
// welches Video zu welchem Song gehört.
const SONGS = [
  // --- 1960er ---
  { title: "Satisfaction", artist: "The Rolling Stones", year: 1965 },
  { title: "Hey Jude", artist: "The Beatles", year: 1968 },
  { title: "Respect", artist: "Aretha Franklin", year: 1967 },
  { title: "Like a Rolling Stone", artist: "Bob Dylan", year: 1965 },
  { title: "House of the Rising Sun", artist: "The Animals", year: 1964 },
  { title: "My Generation", artist: "The Who", year: 1965 },
  { title: "California Dreamin'", artist: "The Mamas & the Papas", year: 1965 },
  { title: "Good Vibrations", artist: "The Beach Boys", year: 1966 },
  { title: "All You Need Is Love", artist: "The Beatles", year: 1967 },
  { title: "Somebody to Love", artist: "Jefferson Airplane", year: 1967 },
  { title: "Marmor, Stein und Eisen bricht", artist: "Drafi Deutscher", year: 1965 },

  // --- 1970er ---
  { title: "Bohemian Rhapsody", artist: "Queen", year: 1975 },
  { title: "Stairway to Heaven", artist: "Led Zeppelin", year: 1971 },
  { title: "Imagine", artist: "John Lennon", year: 1971 },
  { title: "Hotel California", artist: "Eagles", year: 1977 },
  { title: "Dancing Queen", artist: "ABBA", year: 1976 },
  { title: "Stayin' Alive", artist: "Bee Gees", year: 1977 },
  { title: "Le Freak", artist: "Chic", year: 1978 },
  { title: "I Will Survive", artist: "Gloria Gaynor", year: 1978 },
  { title: "Another Brick in the Wall", artist: "Pink Floyd", year: 1979 },
  { title: "Rivers of Babylon", artist: "Boney M.", year: 1978 },
  { title: "Comfortably Numb", artist: "Pink Floyd", year: 1979 },
  { title: "Born to Run", artist: "Bruce Springsteen", year: 1975 },
  { title: "My Sharona", artist: "The Knack", year: 1979 },
  { title: "Video Killed the Radio Star", artist: "The Buggles", year: 1979 },
  { title: "Über den Wolken", artist: "Reinhard Mey", year: 1974 },
  { title: "Griechischer Wein", artist: "Udo Jürgens", year: 1974 },

  // --- 1980er ---
  { title: "Billie Jean", artist: "Michael Jackson", year: 1983 },
  { title: "Thriller", artist: "Michael Jackson", year: 1982 },
  { title: "Sweet Child O' Mine", artist: "Guns N' Roses", year: 1987 },
  { title: "Like a Prayer", artist: "Madonna", year: 1989 },
  { title: "Like a Virgin", artist: "Madonna", year: 1984 },
  { title: "Every Breath You Take", artist: "The Police", year: 1983 },
  { title: "Take On Me", artist: "a-ha", year: 1985 },
  { title: "Sweet Dreams (Are Made of This)", artist: "Eurythmics", year: 1983 },
  { title: "99 Luftballons", artist: "Nena", year: 1983 },
  { title: "Nur geträumt", artist: "Nena", year: 1983 },
  { title: "Ein bisschen Frieden", artist: "Nicole", year: 1982 },
  { title: "Live Is Life", artist: "Opus", year: 1985 },
  { title: "Self Control", artist: "Laura Branigan", year: 1984 },
  { title: "Africa", artist: "Toto", year: 1982 },
  { title: "Livin' on a Prayer", artist: "Bon Jovi", year: 1986 },
  { title: "Rock Me Amadeus", artist: "Falco", year: 1985 },
  { title: "Karma Chameleon", artist: "Culture Club", year: 1983 },
  { title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", year: 1983 },
  { title: "Never Gonna Give You Up", artist: "Rick Astley", year: 1987 },
  { title: "Codo", artist: "Deutsch-Österreichisches Feingefühl (DÖF)", year: 1983 },
  { title: "Da Da Da", artist: "Trio", year: 1982 },
  { title: "Männer", artist: "Herbert Grönemeyer", year: 1984 },
  { title: "Skandal im Sperrbezirk", artist: "Spider Murphy Gang", year: 1981 },
  { title: "Major Tom (Völlig losgelöst)", artist: "Peter Schilling", year: 1982 },

  // --- 1990er ---
  { title: "Smells Like Teen Spirit", artist: "Nirvana", year: 1991 },
  { title: "Wonderwall", artist: "Oasis", year: 1995 },
  { title: "...Baby One More Time", artist: "Britney Spears", year: 1998 },
  { title: "I Will Always Love You", artist: "Whitney Houston", year: 1992 },
  { title: "Mr. Vain", artist: "Culture Beat", year: 1993 },
  { title: "Cotton Eye Joe", artist: "Rednex", year: 1994 },
  { title: "Barbie Girl", artist: "Aqua", year: 1997 },
  { title: "My Heart Will Go On", artist: "Celine Dion", year: 1997 },
  { title: "Torn", artist: "Natalie Imbruglia", year: 1997 },
  { title: "Creep", artist: "Radiohead", year: 1992 },
  { title: "No Scrubs", artist: "TLC", year: 1999 },
  { title: "Livin' la Vida Loca", artist: "Ricky Martin", year: 1999 },
  { title: "Mambo No. 5", artist: "Lou Bega", year: 1999 },
  { title: "Du hast", artist: "Rammstein", year: 1997 },
  { title: "Around the World", artist: "Daft Punk", year: 1997 },
  { title: "Common People", artist: "Pulp", year: 1995 },
  { title: "One", artist: "U2", year: 1991 },
  { title: "Everybody (Backstreet's Back)", artist: "Backstreet Boys", year: 1997 },
  { title: "Believe", artist: "Cher", year: 1998 },
  { title: "Verdammt, ich lieb' dich", artist: "Matthias Reim", year: 1990 },
  { title: "Wahnsinn", artist: "Wolfgang Petry", year: 1993 },

  // --- 2000er ---
  { title: "Crazy in Love", artist: "Beyoncé ft. Jay-Z", year: 2003 },
  { title: "Hey Ya!", artist: "OutKast", year: 2003 },
  { title: "In the End", artist: "Linkin Park", year: 2000 },
  { title: "Numb", artist: "Linkin Park", year: 2003 },
  { title: "Seven Nation Army", artist: "The White Stripes", year: 2003 },
  { title: "Hips Don't Lie", artist: "Shakira", year: 2006 },
  { title: "Umbrella", artist: "Rihanna", year: 2007 },
  { title: "Poker Face", artist: "Lady Gaga", year: 2008 },
  { title: "Viva la Vida", artist: "Coldplay", year: 2008 },
  { title: "Clocks", artist: "Coldplay", year: 2002 },
  { title: "Mr. Brightside", artist: "The Killers", year: 2003 },
  { title: "Dragostea Din Tei", artist: "O-Zone", year: 2003 },
  { title: "Rehab", artist: "Amy Winehouse", year: 2006 },
  { title: "Sex on Fire", artist: "Kings of Leon", year: 2008 },
  { title: "Yeah!", artist: "Usher", year: 2004 },
  { title: "Boulevard of Broken Dreams", artist: "Green Day", year: 2004 },
  { title: "Complicated", artist: "Avril Lavigne", year: 2002 },
  { title: "Toxic", artist: "Britney Spears", year: 2003 },
  { title: "Since U Been Gone", artist: "Kelly Clarkson", year: 2004 },
  { title: "Lose Yourself", artist: "Eminem", year: 2002 },
  { title: "In Da Club", artist: "50 Cent", year: 2003 },
  { title: "I Gotta Feeling", artist: "Black Eyed Peas", year: 2009 },
  { title: "Sonne", artist: "Rammstein", year: 2001 },
  { title: "Wir sind wir", artist: "Paul van Dyk & Peter Heppner", year: 2003 },

  // --- 2010er ---
  { title: "Rolling in the Deep", artist: "Adele", year: 2010 },
  { title: "Somebody That I Used to Know", artist: "Gotye ft. Kimbra", year: 2011 },
  { title: "Get Lucky", artist: "Daft Punk ft. Pharrell Williams", year: 2013 },
  { title: "Happy", artist: "Pharrell Williams", year: 2013 },
  { title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars", year: 2014 },
  { title: "Shape of You", artist: "Ed Sheeran", year: 2017 },
  { title: "Thinking Out Loud", artist: "Ed Sheeran", year: 2014 },
  { title: "Perfect", artist: "Ed Sheeran", year: 2017 },
  { title: "Despacito", artist: "Luis Fonsi ft. Daddy Yankee", year: 2017 },
  { title: "Rockstar", artist: "Post Malone ft. 21 Savage", year: 2017 },
  { title: "Someone You Loved", artist: "Lewis Capaldi", year: 2019 },
  { title: "Roar", artist: "Katy Perry", year: 2013 },
  { title: "Firework", artist: "Katy Perry", year: 2010 },
  { title: "Radioactive", artist: "Imagine Dragons", year: 2012 },
  { title: "Thunder", artist: "Imagine Dragons", year: 2017 },
  { title: "Counting Stars", artist: "OneRepublic", year: 2013 },
  { title: "Wake Me Up", artist: "Avicii", year: 2013 },
  { title: "Levels", artist: "Avicii", year: 2011 },
  { title: "Sugar", artist: "Maroon 5", year: 2015 },
  { title: "Girls Like You", artist: "Maroon 5 ft. Cardi B", year: 2018 },
  { title: "Can't Stop the Feeling!", artist: "Justin Timberlake", year: 2016 },
  { title: "Symphony", artist: "Clean Bandit ft. Zara Larsson", year: 2017 },
  { title: "Rather Be", artist: "Clean Bandit ft. Jess Glynne", year: 2014 },
  { title: "Atemlos durch die Nacht", artist: "Helene Fischer", year: 2013 },
  { title: "Auf uns", artist: "Andreas Bourani", year: 2014 },
  { title: "An Tagen wie diesen", artist: "Die Toten Hosen", year: 2012 },
  { title: "Cheap Thrills", artist: "Sia ft. Sean Paul", year: 2016 },
  { title: "Havana", artist: "Camila Cabello", year: 2017 },
  { title: "Closer", artist: "The Chainsmokers ft. Halsey", year: 2016 },
  { title: "One Dance", artist: "Drake", year: 2016 },
  { title: "Hotline Bling", artist: "Drake", year: 2015 },
  { title: "God's Plan", artist: "Drake", year: 2018 },
  { title: "7 Rings", artist: "Ariana Grande", year: 2019 },
  { title: "Señorita", artist: "Shawn Mendes & Camila Cabello", year: 2019 },
  { title: "Gangnam Style", artist: "Psy", year: 2012 },
  { title: "Titanium", artist: "David Guetta ft. Sia", year: 2011 },
  { title: "Waka Waka (This Time for Africa)", artist: "Shakira", year: 2010 },
  { title: "Only Girl (In the World)", artist: "Rihanna", year: 2010 },
  { title: "We Found Love", artist: "Rihanna ft. Calvin Harris", year: 2011 },
  { title: "Sorry", artist: "Justin Bieber", year: 2015 },
  { title: "Love Yourself", artist: "Justin Bieber", year: 2015 },
  { title: "Faded", artist: "Alan Walker", year: 2015 },
  { title: "This Is What You Came For", artist: "Calvin Harris ft. Rihanna", year: 2016 },
  { title: "HUMBLE.", artist: "Kendrick Lamar", year: 2017 },
  { title: "Feel It Still", artist: "Portugal. The Man", year: 2017 },
  { title: "Party Rock Anthem", artist: "LMFAO", year: 2011 },
  { title: "Roller", artist: "Apache 207", year: 2019 },

  // --- 2020er ---
  { title: "Blinding Lights", artist: "The Weeknd", year: 2019 },
  { title: "Bad Guy", artist: "Billie Eilish", year: 2019 },
  { title: "Old Town Road", artist: "Lil Nas X", year: 2019 },
  { title: "Levitating", artist: "Dua Lipa", year: 2020 },
  { title: "drivers license", artist: "Olivia Rodrigo", year: 2021 },
  { title: "Vampire", artist: "Olivia Rodrigo", year: 2023 },
  { title: "Stay", artist: "The Kid Laroi & Justin Bieber", year: 2021 },
  { title: "As It Was", artist: "Harry Styles", year: 2022 },
  { title: "Flowers", artist: "Miley Cyrus", year: 2023 },
  { title: "Unholy", artist: "Sam Smith & Kim Petras", year: 2022 },
  { title: "Anti-Hero", artist: "Taylor Swift", year: 2022 },
  { title: "Cruel Summer", artist: "Taylor Swift", year: 2019 },
  { title: "Espresso", artist: "Sabrina Carpenter", year: 2024 },
  { title: "Paint The Town Red", artist: "Doja Cat", year: 2023 },
  { title: "Kill Bill", artist: "SZA", year: 2022 },
  { title: "Calm Down", artist: "Rema & Selena Gomez", year: 2022 },
  { title: "Wunder", artist: "Apache 207 & Udo Lindenberg", year: 2021 },
  { title: "Sowieso", artist: "Peter Fox", year: 2023 },
  { title: "Zeit", artist: "Rammstein", year: 2022 },
  { title: "Layla", artist: "DJ Robin & Schürze", year: 2022 },
];
